interface Props {
  strategies: string[];
}

export default function StrategyPanel({ strategies }: Props) {
  return (
    <div className="glass-card p-5 md:p-6" id="strategy-panel">
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        <span className="text-lg">🧭</span>
        <h3
          className="text-sm uppercase tracking-[0.15em] text-gold font-semibold"
          style={{ fontFamily: "var(--font-heading)" }}
        >
          Strategic Recommendations
        </h3>
      </div>

      {/* Strategy list */}
      <div className="space-y-3">
        {strategies.map((strategy, index) => (
          <div
            key={index}
            className="flex items-start gap-3 p-3 rounded-xl bg-surface/50 border border-border/50
                       hover:border-gold/20 transition-all duration-300 group"
          >
            {/* Number badge */}
            <div
              className="w-6 h-6 rounded-full bg-gold/10 border border-gold/20 flex items-center justify-center
                          flex-shrink-0 mt-0.5 group-hover:bg-gold/20 transition-colors"
            >
              <span className="text-gold text-xs font-bold">{index + 1}</span>
            </div>

            {/* Strategy text */}
            <p className="text-pearl/90 text-sm leading-relaxed">{strategy}</p>
          </div>
        ))}
      </div>

      {/* Disclaimer */}
      <div className="mt-4 pt-3 border-t border-border/50">
        <p className="text-mist/50 text-[10px] leading-relaxed">
          ⚠️ This analysis is generated by AI for educational purposes only. It
          does not constitute financial advice. Always consult a qualified
          financial advisor before making investment decisions.
        </p>
      </div>
    </div>
  );
}
